platform :ios, '13.4'

def addModule(name)

pod name, :path => 'DeveloperPods/' + name + '/', :testspecs => ['Tests'] 

end

target 'Weather' do

  addModule 'App'
  addModule 'Core'
  addModule 'Design'
  addModule 'Utils'
  addModule 'CitySearchUserStory'
  addModule 'MainScreen'
  addModule 'WeatherUserStory'
  
  pod "DIGreatness", :git => 'https://github.com/shsanek/DIGreatness'


  target 'WeatherTests' do
  end

  target 'WeatherUITests' do
  end

end
